"""agregar_solicitud_revocacion_y_campos_usuario

Revision ID: 227cbbd93227
Revises: 6c3b23db9533
Create Date: 2026-09-29 12:09:37.598296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227cbbd93227'
down_revision: Union[str, Sequence[str], None] = '6c3b23db9533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    tables = inspector.get_table_names()

    if 'solicitudes_revocacion' not in tables:
        op.create_table(
            'solicitudes_revocacion',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('codigo', sa.String(length=50), nullable=False),
            sa.Column('pedido_id', sa.Integer(), nullable=False),
            sa.Column('usuario_id', sa.Integer(), nullable=False),
            sa.Column('creada_en', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id']),
            sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id']),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_solicitudes_revocacion_codigo'), 'solicitudes_revocacion', ['codigo'], unique=True)
        op.create_index(op.f('ix_solicitudes_revocacion_id'), 'solicitudes_revocacion', ['id'], unique=False)

    usuarios_cols = [c['name'] for c in inspector.get_columns('usuarios')]
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        if 'activo' not in usuarios_cols:
            batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        if 'fecha_baja' not in usuarios_cols:
            batch_op.add_column(sa.Column('fecha_baja', sa.DateTime(), nullable=True))

    with op.batch_alter_table('items_pedido', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('creado_en',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_baja')
        batch_op.drop_column('activo')

    op.drop_index(op.f('ix_solicitudes_revocacion_id'), table_name='solicitudes_revocacion')
    op.drop_index(op.f('ix_solicitudes_revocacion_codigo'), table_name='solicitudes_revocacion')
    op.drop_table('solicitudes_revocacion')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('items_pedido', schema=None) as batch_op:
        batch_op.alter_column('precio_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
