"""agregar acepto_tratamiento a usuarios

Revision ID: fef127e10d7a
Revises: 7118eb416c98
Create Date: 2026-09-28 10:00:16.810091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef127e10d7a'
down_revision: Union[str, Sequence[str], None] = '7118eb416c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acepto_tratamiento', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('acepto_tratamiento')

    # ### end Alembic commands ###
